/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class NodeTest {

  @Test
  public void testNodeCreation() {
    Squirrel squirrel = new Squirrel("Cheeks");
    Node node = new Node(squirrel);

    assertEquals("Cheeks", node.getData().getName());
    assertNull(node.left());
    assertNull(node.right());
  }

  @Test
  public void testSetLeftAndRight() {
    Node root = new Node(new Squirrel("Root"));
    Node leftChild = new Node(new Squirrel("Lefty"));
    Node rightChild = new Node(new Squirrel("Righty"));

    root.setLeft(leftChild);
    root.setRight(rightChild);

    assertEquals("Lefty", root.left().getData().getName());
    assertEquals("Righty", root.right().getData().getName());
  }

  @Test
  public void testLongerTree() {
    Node root = new Node(new Squirrel("Root"));
    Node left = new Node(new Squirrel("Left"));
    Node leftLeft = new Node(new Squirrel("DoubleLeft"));
    Node right = new Node(new Squirrel("Right"));
    Node rightRight = new Node(new Squirrel("DoubleRight"));

    root.setLeft(left);
    left.setLeft(leftLeft);
    root.setRight(right);
    right.setRight(rightRight);

    assertEquals("DoubleLeft", root.left().left().getData().getName());
    assertEquals("DoubleRight", root.right().right().getData().getName());
  }
}
